### ISSUE TITLE
resize windows output in my web browser

### ISSUE THREAD

**Issue by nephaste** [fgallaire/achilterm#3]
I tried achilterm on my Thecus NAS to launch directly midnight commander when invoking port 4200 and ip of my nas within the firefox webui, i modify the achilterm.py to listen on 0.0.0.0 instead of localhost.

all work great...

the only one problem is i cannot resize the output windows. i would to make 100% with and 100% height.

any help is welcome.

Thanks,

**Comment by tejastank** [comment]
@nephaste After making change did you restarted ?
It need to restart after apply change in html or js or might css too.
