### ISSUE TITLE
backspace, Tab effect the browser not the emulator window

### ISSUE THREAD

**Issue by danwanban** [fgallaire/achilterm#4]
Hi,

Trying to use the code. When i enter "backspace" or "tab" in the emulator window, the browser gets them ("backspace" goes back on the browser page list, tab (for linux completion) goes to the next tab on the page, etc.

Any idea ? Tested on chrome and IE, on windows.

Thanks , Best
danny.

**Comment by tejastank** [comment]
https://github.com/tejastank/achilterm/commit/aacff1add19e89f944b6cff13fe70cb7e58ab833

Backspace browser issue shorted, fixed
https://github.com/tejastank/achilterm/

Download latest code
https://github.com/tejastank/achilterm/archive/master.zip

Backspace issue shorted permanently.
